/**
 * Unified streaming API interface
 * Similar to Cline's ApiStream architecture
 * All AI providers (Bedrock, OpenAI, etc.) convert to this format
 */

export type ApiStream = AsyncGenerator<ApiStreamChunk>

export type ApiStreamChunk = 
  | ApiStreamTextChunk 
  | ApiStreamUsageChunk 
  | ApiStreamToolCallsChunk

/**
 * Text content chunk from the model
 */
export interface ApiStreamTextChunk {
  type: "text"
  /**
   * Text content generated by the model
   */
  text: string
}

/**
 * Usage statistics chunk
 */
export interface ApiStreamUsageChunk {
  type: "usage"
  inputTokens: number
  outputTokens: number
  cacheWriteTokens?: number
  cacheReadTokens?: number
}

/**
 * Tool call chunk
 */
export interface ApiStreamToolCallsChunk {
  type: "tool_calls"
  /**
   * The tool call information
   */
  tool_call: ApiStreamToolCall
}

/**
 * Tool call details
 */
export interface ApiStreamToolCall {
  /**
   * The call ID associated with this tool call
   */
  id: string
  /**
   * Name of the tool
   */
  name: string
  /**
   * The arguments passed to the tool execution
   */
  input: any
}
